[package]
name = "layer_2"
version = "0.1.0"
authors = ["Ioan Stănilă <ioanstanilais@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
